kino/kino/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kinoteatr.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kino/kinoteatr/urls.py
from django.urls import path
from . import views
from .views import RegisterUser, LoginUser, LogoutUser

urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:pk>/', views.movie_detail, name='movie_detail'),
    path('movie/<int:pk>/sessions/', views.movie_sessions, name='movie_sessions'),
    path('session/<int:pk>/', views.session_detail, name='session_detail'),
    path('book/<int:session_id>/', views.book_ticket, name='book_ticket'),
    path('actor/', views.actor_list, name='actor_list'),
    path('actor/<int:pk>/', views.actor_detail, name='actor_detail'),
    path('directors/', views.director_list, name='director_list'),
    path('directors/<int:pk>/', views.director_detail, name='director_detail'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutUser.as_view(), name='logout'),
    path('movies/', views.movie_list, name='movie_list'),

]

kino/kinoteatr/models.py
from django.db import models
from django.contrib.auth.models import User


class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name


class Director(models.Model):  #
    name = models.CharField(max_length=150)
    foto = models.ImageField(upload_to='media/fotodirector')

    def __str__(self):
        return self.name


class Actor(models.Model):
    name = models.CharField(max_length=150)
    foto = models.ImageField(upload_to='media/fotoactor')

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    director = models.ForeignKey(Director, on_delete=models.CASCADE)
    actor = models.ManyToManyField(Actor)
    poster = models.ImageField(upload_to='media/fotoposter')

    def __str__(self):
        return self.title


class Session(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    time = models.DateTimeField()
    hall = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.movie.title} - {self.time}'


class Ticket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    seat = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.user.username} - {self.session.movie.title} - {self.seat}"

kino/kinoteatr/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Ticket

class NewUser(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class AuthenticationUser(AuthenticationForm):
    pass

class TicketBooking(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['session', 'seat']

kino/kinoteatr/views.py
from django.shortcuts import render, get_object_or_404
from .models import Movie, Session, Ticket, Actor, Director
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
# регистрация
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.views.generic import CreateView
from .forms import NewUser, AuthenticationUser, TicketBooking
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy


def index(request):
    movies = Movie.objects.all()
    return render(request, 'cinema/index.html', {'movies': movies})


def movie_list(request):
    movies = Movie.objects.all()
    return render(request, 'cinema/movie_list.html', {'movies': movies})


def movie_detail(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    return render(request, 'cinema/movie_detail.html', {'movie': movie})


def movie_sessions(request, pk):
    movie = get_object_or_404(Movie, pk=pk)
    sessions = Session.objects.filter(movie=movie)
    return render(request, 'cinema/movie_sessions.html', {'movie': movie, 'sessions': sessions})


def session_detail(request, pk):
    session = get_object_or_404(Session, pk=pk)
    return render(request, 'cinema/session_detail.html', {'session': session})


@login_required
def book_ticket(request, session_id):
    session = get_object_or_404(Session, pk=session_id)
    if request.method == 'POST':
        form = TicketBooking(request.POST)
        if form.is_valid():
            # Проверка наличия места
            seat = form.cleaned_data['seat']
            if not Ticket.objects.filter(session=session, seat=seat).exists():
                ticket = form.save(commit=False)
                ticket.user = request.user
                ticket.session = session
                ticket.save()
                return HttpResponseRedirect(reverse('session_detail', args=[session_id]))
            else:
                form.add_error('seat', 'Это место уже занято.')
    else:
        form = TicketBooking()

    return render(request, 'cinema/book_ticket.html', {'form': form, 'session': session})


def actor_detail(request, pk):
    actor = get_object_or_404(Actor, pk=pk)
    return render(request, 'cinema/actor_detail.html', {'actor': actor})


def actor_list(request):
    actors = Actor.objects.all()
    return render(request, 'cinema/actors.html', {'actors': actors})


def director_list(request):
    directors = Director.objects.all()
    return render(request, 'cinema/directors.html', {'directors': directors})


def director_detail(request, pk):
    director = get_object_or_404(Director, pk=pk)
    return render(request, 'cinema/director_detail.html', {'director': director})


class RegisterUser(CreateView):
    template_name = 'registration/register.html'
    form_class = NewUser
    success_url = '/'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)


class LoginUser(LoginView):
    template_name = 'registration/login.html'
    success_url = '/'


class LogoutUser(LogoutView):
    next_page = reverse_lazy('index')

kino/kinoteatr/templates/cinema/actor_detail.html
{% extends 'cinema/base.html' %}

{% block title %}Список Актеров - Кинотеатр{% endblock %}

{% block content %}

<h1>{{ actor.name }}</h1>
<img src="{{ actor.foto.url }}" alt="{{ actor.name }}">
{% if actor.movie_set.all %}
    <h2>Фильмы, в которых снимался(а) {{ actor.name }}:</h2>
    <ul>
        {% for movie in actor.movie_set.all %}
            <li>
                <a href="{% url 'movie_detail' movie.pk %}">{{ movie.title }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Данный актер не участвовал в съёмках ни в одном фильме.</p>
{% endif %}


{% endblock %}

kino/kinoteatr/templates/cinema/actors.html
{% extends 'cinema/base.html' %}

{% block title %}Список Актеров - Кинотеатр{% endblock %}

{% block content %}
<h1>Список Актеров</h1>
<div class="actors-container">
    {% for actor in actors %}
    <div class="actor-card">
        <a href="{% url 'actor_detail' actor.pk %}">
            <img src="{{ actor.foto.url }}" alt="{{ actor.name }}">
            <p>{{ actor.name }}</p>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

kino/kinoteatr/templates/cinema/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Кинотеатр{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
<header>
    <div class="header-content">
        <a href="{% url 'index' %}"><h1>Кинотеатр</h1></a>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="/movies">Фильмы</a></li>
                <li><a href="/directors">Режиссеры</a></li>
                <li><a href="/actor">Актеры</a></li>
                <li><a href="/admin">Админ панель</a></li>
                <li><a href="/register">Регистрация</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Выход</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}">Вход</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</header>

<main>
    {% block content %}

    {% endblock %}
</main>

<footer>
    <p>&copy; 2024 Кинотеатр.</p>
</footer>
</body>
</html>

kino/kinoteatr/templates/cinema/book_ticket.html
{% extends 'cinema/base.html' %}

{% block title %}Бронирование билета{% endblock %}

{% block content %}
<h2>Бронирование билета</h2>
<p><strong>Фильм:</strong> {{ session.movie.title }}</p>
<p><strong>Время:</strong> {{ session.time }}</p>
<p><strong>Зал:</strong> {{ session.hall }}</p>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Забронировать</button>
</form>
{% endblock %}

kino/kinoteatr/templates/cinema/director_detail.html
{% extends 'cinema/base.html' %}

{% block title %}{{ director.name }}{% endblock %}

{% block content %}
<div class="director-detail">

    <h2>{{ director.name }}</h2>
    <img src="{{ director.foto.url }}" alt="{{ director.name }}">
    {% if director.movie_set.all %}
    <h2>Фильмы, в которых снимался(а) {{ director.name }}:</h2>
    <ul>
        {% for movie in director.movie_set.all %}
        <li>
            <a href="{% url 'movie_detail' movie.pk %}">{{ movie.title }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Данный актер не участвовал в съёмках ни в одном фильме.</p>
    {% endif %}
</div>
{% endblock %}

kino/kinoteatr/templates/cinema/directors.html
{% extends 'cinema/base.html' %}

{% block title %}Режиссеры{% endblock %}

{% block content %}
<h2>Список режиссеров</h2>
<div class="directors-container">
    {% for director in directors %}
        <div class="director-card">
            <a href="{% url 'director_detail' director.pk %}">
                <img src="{{ director.foto.url }}" alt="{{ director.name }}">
                <p>{{ director.name }}</p>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

kino/kinoteatr/templates/cinema/index.html
{% extends 'cinema/base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
<h2>Фильмы</h2>
{% if movies %}
<ul class="movie-list">
    {% for movie in movies %}
    <li class="movie-item">
        <img src="{{ movie.poster.url }}" alt="{{ movie.title }} poster" class="movie-poster">
        <div class="movie-details">
            <h3>{{ movie.title }}</h3>
            <p>{{ movie.description }}</p>
            <p><strong>Жанр:</strong> {{ movie.genre }}</p>
            <p><strong>Режиссер:</strong> <a href="/directors/{{ movie.director.pk }}">{{ movie.director.name }}</a></p>
            <a href="{% url 'movie_sessions' movie.pk %}" class="movie-link">Посмотреть сеансы</a>
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>Фильмы не найдены.</p>
{% endif %}
{% endblock %}

kino/kinoteatr/templates/cinema/movie_detail.html
{% extends 'cinema/base.html' %}

{% block title %}Детали Фильма: {{ movie.title }}{% endblock %}

{% block content %}
<div class="movie-details-container">
    <h2>Детали Фильма:</h2>
    <img src="{{ movie.poster.url }}" alt="{{ movie.title }} poster">
    <p><strong>Фильм:</strong> {{ movie.title }}</p>

    <p><strong>Режиссер:</strong> {{ movie.director.name }}</p>
    {% if movie.actor.exists %}
        <p><strong>Актеры:</strong></p>
        <ul>
            {% for actor in movie.actor.all %}
                <li>{{ actor.name }}</li>
            {% endfor %}
        </ul>
    {% else %}
        <p><strong>Актеры:</strong> Нет информации об актерах.</p>
    {% endif %}
    <p><strong>Краткое описание:</strong> {{ movie.description }}</p>
</div>
{% endblock %}

kino/kinoteatr/templates/cinema/movie_list.html
{% extends 'cinema/base.html' %}

{% block title %}Список Фильмов - Кинотеатр{% endblock %}

{% block content %}
<h1>Список Фильмов</h1>
<div class="movies-container">
    {% for movie in movies %}
    <div class="movie-card">
        {% if movie.pk %}
            <a href="{% url 'movie_detail' movie.pk %}">
                <img src="{{ movie.poster.url }}" alt="{{ movie.title }}">
                <p>{{ movie.title }}</p>
            </a>
        {% else %}
            <div>
                <img src="{{ movie.poster.url }}" alt="{{ movie.title }}">
                <p>{{ movie.title }} (нет информации о фильме)</p>
            </div>
        {% endif %}
    </div>
    {% endfor %}
</div>
{% endblock %}

kino/kinoteatr/templates/cinema/movie_sessions.html
{% extends 'cinema/base.html' %}

{% block title %}Сеансы для {{ movie.title }}{% endblock %}

{% block content %}
<h2>Сеансы для: {{ movie.title }}</h2>
<ul>
    {% for session in sessions %}
        <li>
            <img src="{{ movie.poster.url }}">
            <p><strong>Время:</strong> {{ session.time }}</p>
            <p><strong>Зал:</strong> {{ session.hall }}</p>
            <a href="{% url 'session_detail' session.pk %}" class="movie-link">Подробнее</a>

        </li>
    {% endfor %}
</ul>
{% endblock %}

kino/kinoteatr/templates/cinema/session_detail.html
{% extends 'cinema/base.html' %}

{% block title %}Детали сеанса{% endblock %}

{% block content %}
<h2>Детали сеанса: </h2>
<img src="{{ movie.poster.url }}">
<p><strong>Фильм:</strong> {{ session.movie.title }}</p>
<p><strong>Время:</strong> {{ session.time }}</p>
<p><strong>Зал:</strong> {{ session.hall }}</p>

<a href="{% url 'book_ticket' session.pk %}" class="movie-link">Забронировать билет</a>

<h3>Забронированные места</h3>
<ul>
    {% for ticket in session.ticket_set.all %}
    <li>{{ ticket.seat }} ({{ ticket.user.username }})</li>
    {% endfor %}
</ul>
{% endblock %}